version: 2.1

jobs:
  saluda:
    parameters:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo adios

workflows:
  wf1:
    jobs:
      - saluda
      - despidete
  wf2:
    jobs:
      - saluda
      - despidete:
        requires:
          - saluda
  wf3:
    jobs:
      - saluda
      - approval:
        type: approval
        requires:
          - saluda
      - despidete:
        requires:
          - approval
