version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo hola

  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo pre adios
      - run: echo adios

workflows:
  workflow1:
    jobs:
      - saluda
      - despidete

  workflow2:
    jobs:
      - saluda
      - despidete:
        requires:
          - saluda

  nightly:
    triggers:
      - schedule:
        cron: '48 10 * * *'
        filters:
          branches:
            only: master

    jobs:
      - saluda
      - despidete:
        requires:
          - saluda
